Documents/freshfix/fresh/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import home,editabout,delete_abouts,listAbout,edit_about,add_about,editslide,edit_slide,delete_slide,add_slider,listSlider,addSlider,delete_logo, listLogos,getLogo,add_logo,update_service,edit_service,delete_service,listServices,about,service,blog,blogDetails,serviceDetails,contact,privacy,dashboard,addServices,add_service
from userauths.views import register,login_view,logout_view, check_mail,reset_password
from .views import addTeam,sendToMail,edit_team,add_team,delete_team,listTeam,update_team,addUs,add_us,listUs,delete_us,edit_us,update_us
from .views import addtestimonials,save_testimonials, listTestimonials,delete_testimonials,edit_testimonials,update_testimonial
from .views import  addBlog,add_Blog,listBlog,delete_Blog,edit_Blog,update_Blog,add_about2
from .views import  addContactAddress, add_ContactAddress, listContactAddress, delete_ContactAddress, edit_ContactAddress, update_ContactAddress
from .views import  blogByCategory,add_about3,addCategory,add_category,listCategory,delete_Category,edit_Category,update_Category,add_blog
from .views import getContactImage,listContactImage,add_ContactImage,delete_ContactImage, sendComment,listComments,delete_comment
from .views import  addPrivacy,add_PrivacyPolicy,listPrivacyPolicy,delete_PrivacyPolicy,edit_PrivacyPolicy,update_PrivacyPolicy
from .views import listUser,delete_User,listCode,delete_Code,edit_user,update_user

app_name = "fresh"

urlpatterns = [

    path("check-mail", check_mail, name="check_mail"),
    path("list-user", listUser, name="listUser"),
    path("delete-user/<int:id>/", delete_User, name="delete_User"),
    path("edit-user/<int:id>/", edit_user, name="edit_user"),
    path("update-user", update_user, name="update_user"),
    

    path("list-code", listCode, name="listCode"),
    path("delete-code/<int:id>/", delete_Code, name="delete_Code"),

    


    path("add-policy", addPrivacy, name="addPrivacy"),
    path("save-policy", add_PrivacyPolicy, name="add_PrivacyPolicy"),
    path("list-policy", listPrivacyPolicy, name="listPrivacyPolicy"),
    path("delete-policy/<int:id>/", delete_PrivacyPolicy, name="delete_PrivacyPolicy"),
    path("edit-policy/<int:id>/", edit_PrivacyPolicy, name="edit_PrivacyPolicy"),
    path("update-policy", update_PrivacyPolicy, name="update_PrivacyPolicy"),


    path("add-contact-image", getContactImage, name="getContactImage"),
    path("save-contact-image", listContactImage, name="listContactImage"),
    path("list-contact-image", add_ContactImage, name="add_ContactImage"),
    path("delete-contact-image/<int:id>/", delete_ContactImage, name="delete_ContactImage"),



    path("add-contact-address", addContactAddress, name="addContactAddress"),
    path("save-contact-address", add_ContactAddress, name="add_ContactAddress"),
    path("list-contact-address", listContactAddress, name="listContactAddress"),
    path("delete-contact-address/<int:id>/", delete_ContactAddress, name="delete_ContactAddress"),
    path("edit-contact-address/<int:id>/", edit_ContactAddress, name="edit_ContactAddress"),
    path("update-contact-address", update_ContactAddress, name="update_ContactAddress"), 
    
    
    


    path("add-Blog", addBlog, name="addBlog"),
    path("add-Blog", add_Blog, name="add_Blog"),
    path("list-Blog", listBlog, name="listBlog"),
    path("delete-Blog/<int:id>/", delete_Blog, name="delete_Blog"),
    path("edit-Blog/<int:id>/", edit_Blog, name="edit_Blog"),
    path("update-Blog", update_Blog, name="update_Blog"),
    path("submit-Blog", add_blog, name="add_blog"),
    


    path("add-Category", addCategory, name="addCategory"),
    path("add-Category", add_category, name="add_category"),
    path("list-Category", listCategory, name="listCategory"),
    path("delete-Category/<int:id>/", delete_Category, name="delete_Category"),
    path("edit-Category/<int:id>/", edit_Category, name="edit_Category"),
    path("update-Category", update_Category, name="update_Category"),










    path("add-testimonials", addtestimonials, name="addtestimonials"),
    path("save_testimonials", save_testimonials, name="save_testimonials"),
    path("list-testimonials", listTestimonials, name="listTestimonials"),
    path("delete_testimonials/<int:id>/", delete_testimonials, name="delete_testimonials"),
    path("edit_testimonials/<int:id>/", edit_testimonials, name="edit_testimonials"),
    path("update-testimonial", update_testimonial, name="update_testimonial"),
    path('', home, name='home'),
    path('about', about, name='about'),
    path('service', service, name='service'),
    path('blog', blog, name='blog'),
    path('blog-detail/<slug:slug>/', blogDetails, name='blogDetails'),
    path('blog-category/<slug:slug>/', blogByCategory, name='blogByCategory'),
    path('password-reset/<str:email>/', reset_password, name='reset_password'),
    
    
    path('service-detail/<slug:slug>', serviceDetails, name='serviceDetails'),
    path('contact', contact, name='contact'),
    path('addTeam', addTeam, name='addTeam'),
    path('add_team', add_team, name='add_team'),
    path('privacy', privacy, name='privacy'),
     path("register", register, name="register"),
     path("login", login_view, name="login_view"),
     path("logout", logout_view, name="logout_view"),
     path("dashboard", dashboard, name="dashboard"),
     path("add_logo", add_logo, name="add_logo"),
     path("add_about", add_about, name="add_about"),
     path("add_about", add_about2, name="add_about2"),
     path("add_about_", add_about3, name="add_about3"),
     path("list-about", listAbout, name="listAbout"),
     path("update-about", editabout, name="editabout"),     
     path("edit-about/<int:id>/", edit_about, name="edit_about"),
     path("delete-about/<int:id>/", delete_abouts, name="delete_abouts"),     
     path("getLogo", getLogo, name="getLogo"),
     path("update-service", update_service, name="update_service"),
     path("update-team", update_team, name="update_team"),
     path("add-services", addServices, name="addServices"),
     path('add-service/', add_service, name='add_service'),
     path('add-slider/', add_slider, name='add_slider'),
     path('add-slider/', addSlider, name='addSlider'),
     path('list-service/', listServices, name='listServices'),
     path('list-team/', listTeam, name='listTeam'),
     path('list-logos/', listLogos, name='listLogos'),
     path('list-slide/', listSlider, name='listSlider'),
     path('delete-service/<int:id>/', delete_service, name='delete_service'),
     path('delete-team/<int:id>/', delete_team, name='delete_team'),
     path('delete-logo/<int:id>/', delete_logo, name='delete_logo'),
     path('edit-service/<int:id>/', edit_service, name='edit_service'),
     path('edit-team/<int:id>/', edit_team, name='edit_team'),
     path('edit-slide/<int:id>/', edit_slide, name='edit_slide'),
     path('update-slide', editslide, name='editslide'),
     path('delete-slide/<int:id>/', delete_slide, name='delete_slide'),
    path("addus", addUs, name="addUs"),
    path("add-us", add_us, name="add_us"),
    path("list-us", listUs, name="listUs"),
    path("delete-us/<int:id>/", delete_us, name="delete_us"),
    path("edit-us/<int:id>/", edit_us, name="edit_us"),
    path("update-us", update_us, name="update_us"),
    path("send-mail", sendToMail, name="sendToMail"),     
    path("send-comment", sendComment, name="sendComment"),     
    path("list-comment", listComments, name="listComments"),     
    path("delete_comment/<int:id>/", delete_comment, name="delete_comment"),     
    
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Documents/freshfix/freshfix/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fresh.urls')),
]

Documents/freshfix/templates/frontpages/blogbycategory.html
{% extends 'partials/base.html' %}
{% load static %}

    <!--End header-->
    
    {% block meta_tags %}
        <meta name="description" content="International School & Job Portal - Admissions and Career Opportunities for Global Students and Professionals">
        <meta name="keywords" content="International School, Admissions, Job Portal, Career Opportunities, Global Students, Global Jobs, Education, Apply Now, Employment, University, Scholarships">
        <title>International School & Job Portal - Admissions & Career Opportunities</title>
    {% endblock meta_tags %}

    


{%  block content %}


<body>
    <div class="body-overlay"></div>
    <!-- Loader Start -->
 
    <!-- Loader End -->

    <!-- back to top start -->
    {% include 'partials/backtotop.html' %}
    <!-- back to top end -->

    <!-- Search Popup Start -->
    {% include 'partials/searchpopup.html' %}
    <!-- Search Popup End-->

    <!-- cart mini area start -->
    {% include 'partials/cartmini.html' %}
    <!-- cart mini area end -->

    <!-- Hamburger start -->
    {% include 'partials/harmburger.html' %}
    <!-- Hamburger end -->

    <!-- Header Area Start -->
    {% include 'partials/header.html' %}
    <!-- Header Area End-->

    <!-- Sticky Header Area Start -->
      {% include 'partials/fixedheadertop.html' %}
    <!-- Sticky Header Area End -->

    <main id="primary" class="site-main">

        <!-- Breadcrumb Area Start-->
        <section class="tj-breadcrumb-area" data-background="{% static 'assets/images/breadcrumb/breadcrumb-bg1.jpg' %}">
            <div class="container">
                <div class="row">
                    <div class="tj-breadcrumb-content text-center">
                        <h2 class="tj-breadcrumb-title">Blog </h2>
                        <p class="tj-breadcrumb-body"><span><a href="index.html">Home</a></span> <span class="spacing"><svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" clip-rule="evenodd" d="M16.1639 8.42265C16.4818 8.74057 16.4818 9.25948 16.1639 9.57739L9.93661 15.8045C9.6182 16.1229 9.10024 16.1229 8.78187 15.8045L8.43354 15.4562C8.11485 15.1375 8.11478 14.6198 8.4335 14.301L13.1574 9.57753C13.4762 9.25884 13.4762 8.74106 13.1574 8.42237L8.43354 3.69885C8.11478 3.38012 8.11481 2.86248 8.43357 2.54375L8.7819 2.19542C9.09982 1.87751 9.61872 1.87751 9.93664 2.19542L16.1639 8.42265ZM3.34094 2.19535C3.02271 1.87708 2.50426 1.87712 2.18602 2.19535L1.8377 2.54368C1.5196 2.86178 1.51957 3.38068 1.8377 3.69881L6.5614 8.42237C6.88012 8.7411 6.88012 9.25881 6.5614 9.57753L1.83766 14.3011C1.51943 14.6193 1.51946 15.138 1.83766 15.4562L2.18599 15.8045C2.50436 16.1229 3.02253 16.1229 3.34091 15.8045L9.01506 10.1302C10.6067 11.7203 10.2041 11.317 9.01622 10.129L9.56782 9.57739C9.88595 9.25926 9.88591 8.74074 9.56782 8.42262L3.34094 2.19535Z" fill="white" />
                          </svg></span> Blog </p>
                    </div>
                </div>
            </div>
            <div class="tj-breadcrumb-bg-shape">
                <img src="{% static 'assets/images/breadcrumb/breadcrumb-bg-shape.png' %}" alt="">
            </div>
        </section>
        <!-- Breadcrumb Area End-->

        <!-- Blog Area Start-->
        <section class="full-width tj-posts__area tj-blog-page">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 ">
                        <div class="tj-post__container tj-post-wrapper">

                            {% if blogbycategory %}
                            {% for blog in blogbycategory %}
                            <article class="tj__post tj-post-item wow fadeInUp" data-wow-delay=".3s">
                                <div class="blog-thumb-image">
                                    <a href="{% url 'fresh:blogDetails' blog.slug %}">
                                        {% if blog.image %}
                                        <img src="{{ blog.image.url }}" class="img-fluid" alt="Blog Image">
                                        {% else %}
                                            <p>No image available</p>
                                        {% endif %} 
                                    </a>
                                </div>
                                <div class="tj-post__content">
                                    <div class="tj-post__meta entry-meta blog-meta">
                                        <span><i class="flaticon-calendar"></i> {{ blog.created_at }} </span>
                                        <span><i class="flaticon-user"></i> By<a href="#"> Admin</a></span>
                                        <!-- <span><i class="flaticon-comment"></i><a href="#">Comments ({{comments_count}})</a></span> -->
                                    </div>
                                    <div class="details-title">
                                        <h3 class="tj-post__title entry-title title">
                                            <a href="{% url 'fresh:blogDetails' blog.slug %}"> {{blog.name}} </a>
                                        </h3>
                                    </div>
                                    <div class="post_excerpt">
                                        {{blog.description|safe|truncatechars:200}}
                                    </div>
                                    <div class="tj-post__btn blog-button d-flex">
                                        <a class="tj-primary-btn tj-hover-btn" href="{% url 'fresh:blogDetails' blog.slug %}">Read More <span><i class="fa-light fa-arrow-right"></i></span>
                                            <div class="tj-hover-btn-circle-dot"></div>
                                        </a>
                                    </div>
                                </div>
                                <div class="tj-clearfix"></div>
                            </article>
                            {% endfor %}
                            {% else %}
                            <p>No results for your search</p>
                           {% endif %}
                        
                        <!-- Pagination -->
                        <div class="tj__pagination wow fadeInUp" data-wow-delay=".6s">
                            <ul>
                                {% if page_obj.has_previous %}
                                    <li><a class="page-numbers" href="?page=1">First</a></li>
                                    <li><a class="page-numbers" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                                {% endif %}
                                
                                <li><span class="page-numbers current">{{ page_obj.number }}</span></li>
                                
                                {% if page_obj.has_next %}
                                    <li><a class="page-numbers" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                                    <li><a class="page-numbers" href="?page={{ page_obj.paginator.num_pages }}">Last</a></li>
                                {% endif %}
                            </ul>
                        </div>
                        


                        </div>
                    </div>
                    <div class="col-lg-4">
                        <aside class="tj-main__sidebar tj-main-sidebar wow fadeInUp" data-wow-delay=".5s">
                            <div class="tj-sidebar__widget tj-blog-widget widget_search wow fadeInUp" data-wow-delay=".6s">
                                <div class="tj-widget__search sidebar-search">
                                    <form action="#">
                                        <input type="text" value="" required="" name="s" placeholder="Search...">
                                        <button type="submit"> <i class="fa-regular fa-magnifying-glass"></i> </button>
                                    </form>
                                </div>
                            </div>

                            <div class="tj-sidebar__widget widget_categories stander wow fadeInUp" data-wow-delay=".7s">
                                <h3 class="widget_categories-title">Categories</h3>
                                <nav>
                                  {% include 'partials/categories.html' %}
                                </nav>
                            </div>
                            <div id="tj-recent-posts-2" class="tj-sidebar__widget tj-blog-widget tj_recent_posts wow fadeInUp" data-wow-delay=".8s">
                                <h3 class="tj-sidebar-widget__title side-title"> Recent Posts </h3>
                                <div class="sidebar-recent-post">
                                    {% include 'partials/recentpost.html' %}
                                </div>
    
                            </div>
                            <div id="tag_cloud-2" class="tj-sidebar__widget tj-blog-widget widget_tag_cloud wow fadeInUp" data-wow-delay=".9s">
                                <h3 class="tj-sidebar-widget__title side-title">Popular Tages</h3>
                                <nav aria-label="Popular Tages">
                                    <div class="tagcloud">
                                        {% include 'partials/populartags.html' %}
                                    </div>
                                </nav>
                            </div>
                        </aside>
                    </div>
                    <!--!sidebar -->
                </div>
            </div>
        </section>
        <!-- Blog Area End-->

    </main>

    <!-- Footer Area Start-->
    {% include 'partials/footer.html' %}
    <!-- Footer Area End-->

 
</body>

{% endblock content %}

Documents/freshfix/templates/frontpages/privacy.html
{% extends 'partials/base.html' %}
{% load static %}

    <!--End header-->
    
    {% block meta_tags %}
        <meta name="description" content="International School & Job Portal - Admissions and Career Opportunities for Global Students and Professionals">
        <meta name="keywords" content="International School, Admissions, Job Portal, Career Opportunities, Global Students, Global Jobs, Education, Apply Now, Employment, University, Scholarships">
        <title>International School & Job Portal - Admissions & Career Opportunities</title>
    {% endblock meta_tags %}

    


{%  block content %}

<body>
    <div class="body-overlay"></div>

     <!-- Loader Start -->
 
    <!-- Loader End -->

    <!-- back to top start -->
    {% include 'partials/backtotop.html' %}
    <!-- back to top end -->

    <!-- Search Popup Start -->
    {% include 'partials/searchpopup.html' %}
    <!-- Search Popup End-->

    <!-- cart mini area start -->
    {% include 'partials/cartmini.html' %}
    <!-- cart mini area end -->

    <!-- Hamburger start -->
    {% include 'partials/harmburger.html' %}
    <!-- Hamburger end -->

    <!-- Header Area Start -->
    {% include 'partials/header.html' %}
    <!-- Header Area End-->

    <!-- Sticky Header Area Start -->
      {% include 'partials/fixedheadertop.html' %}
    <!-- Sticky Header Area End -->

    <main id="primary" class="site-main">

        <!-- Breadcrumb Area Start-->
        <section class="tj-breadcrumb-area" data-background="{% static 'assets/images/breadcrumb/breadcrumb-bg1.jpg' %}">
            <div class="container">
                <div class="row">
                    <div class="tj-breadcrumb-content text-center">
                        <h2 class="tj-breadcrumb-title tj-char-animation">Privacy</h2>
                        <p class="tj-breadcrumb-body"><span><a href="index.html">Home</a></span> <span class="spacing"><svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" clip-rule="evenodd" d="M16.1639 8.42265C16.4818 8.74057 16.4818 9.25948 16.1639 9.57739L9.93661 15.8045C9.6182 16.1229 9.10024 16.1229 8.78187 15.8045L8.43354 15.4562C8.11485 15.1375 8.11478 14.6198 8.4335 14.301L13.1574 9.57753C13.4762 9.25884 13.4762 8.74106 13.1574 8.42237L8.43354 3.69885C8.11478 3.38012 8.11481 2.86248 8.43357 2.54375L8.7819 2.19542C9.09982 1.87751 9.61872 1.87751 9.93664 2.19542L16.1639 8.42265ZM3.34094 2.19535C3.02271 1.87708 2.50426 1.87712 2.18602 2.19535L1.8377 2.54368C1.5196 2.86178 1.51957 3.38068 1.8377 3.69881L6.5614 8.42237C6.88012 8.7411 6.88012 9.25881 6.5614 9.57753L1.83766 14.3011C1.51943 14.6193 1.51946 15.138 1.83766 15.4562L2.18599 15.8045C2.50436 16.1229 3.02253 16.1229 3.34091 15.8045L9.01506 10.1302C10.6067 11.7203 10.2041 11.317 9.01622 10.129L9.56782 9.57739C9.88595 9.25926 9.88591 8.74074 9.56782 8.42262L3.34094 2.19535Z" fill="white" />
                          </svg></span> Privacy</p>
                    </div>
                </div>
            </div>
            <div class="tj-breadcrumb-bg-shape">
                <img src="assets/images/breadcrumb/breadcrumb-bg-shape.png" alt="">
            </div>
        </section>
        <!-- Breadcrumb Area End-->

        <!-- Blog-Page Area Start-->
        <section class="full-width tj-posts__area tj-blog-page">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="tj-post__container tj-post-wrapper">
                            <article class="tj__post tj-post-item details wow fadeInUp" data-wow-delay=".2s">
                             
                                <div class="tj-post__content">

                                    <div class="details-title">
                                        <h3 class="tj-post__title entry-title title tj-char-animation">
                                            Privacy</h3>
                                    </div>

                                    <div class="tj-post__meta entry-meta blog-meta">
                                        <span><i class="flaticon-calendar"></i> {{privacy.created_at}} </span>
                                        <span><i class="flaticon-user"></i><span><a href="#">By Admin</a></span></span>
                                      
                                    </div>
                                  
                                    <div class="post_excerpt mb-3">
                                         {{privacy.description|safe}}
                                    </div>
                              
                                </div>
                                <div class="tj-clearfix"></div>
                            </article> 
                            <div class="tj-post__content wow fadeInUp" data-wow-delay=".4s">
                                <div class="details-title">
                                    <h3 class="tj-post__title entry-title title tj-char-animation">Customize the cleaning services to fit my needs</h3>
                                </div>
                                <div class="post_excerpt mb-3">
                                    Ensuring medical facilities meet hygiene and sanitation standards, including the cleaning of examination rooms, waiting areas, and equipment. Specialized cleaning for factories, warehouses, and other industrial spaces, often involving heavy-duty equipment cleaning and stain removal for furniture.
                                </div>
                                <div class="post_excerpt">
                                    Compare pricing structures and understand what is included in the quoted price. Some services charge by the hour, while others offer flat rates that can tailor their offerings to meet your specific.
                                </div>
                            </div>
                
                            <div class="tj-post__content wow fadeInUp" data-wow-delay=".6s">
                                <div class="post_excerpt mb-3">
                                    Review any contracts or service agreements carefully, including terms of service, cancellation policies, and service is guarantees. If environmental impact is important to you, look for services that offer eco-friendly cleaning products or and practices. Ensure the service is insured and bonded to protect against damages or theft.
                                </div>
                            </div>
                         
                           
                        </div>
                    </div>
                  
                    <!--!sidebar -->
                </div>
            </div>
        </section>
        <!-- Blog-Page Area End-->

    </main>

    <!-- Footer Area Start-->
    {% include 'partials/footer.html' %}
    <!-- Footer Area End-->

 
</body>

{% endblock content %}

Documents/freshfix/templates/frontpages/service.html
{% extends 'partials/base.html' %}
{% load static %}

    <!--End header-->
    
    {% block meta_tags %}
        <meta name="description" content="International School & Job Portal - Admissions and Career Opportunities for Global Students and Professionals">
        <meta name="keywords" content="International School, Admissions, Job Portal, Career Opportunities, Global Students, Global Jobs, Education, Apply Now, Employment, University, Scholarships">
        <title>International School & Job Portal - Admissions & Career Opportunities</title>
    {% endblock meta_tags %}

    


{%  block content %}
<body>
    <div class="body-overlay"></div>

   <!-- Loader Start -->
 
    <!-- Loader End -->

    <!-- back to top start -->
    {% include 'partials/backtotop.html' %}
    <!-- back to top end -->

    <!-- Search Popup Start -->
    {% include 'partials/searchpopup.html' %}
    <!-- Search Popup End-->

    <!-- cart mini area start -->
    {% include 'partials/cartmini.html' %}
    <!-- cart mini area end -->

    <!-- Hamburger start -->
    {% include 'partials/harmburger.html' %}
    <!-- Hamburger end -->

    <!-- Header Area Start -->
    {% include 'partials/header.html' %}
    <!-- Header Area End-->

    <!-- Sticky Header Area Start -->
      {% include 'partials/fixedheadertop.html' %}

    <main id="primary" class="site-main">

        <!-- Breadcrumb Area Start-->
        <section class="tj-breadcrumb-area" data-background="{% static 'assets/images/breadcrumb/breadcrumb-bg1.jpg' %}">
            <div class="container">
                <div class="row">
                    <div class="tj-breadcrumb-content text-center">
                        <h2 class="tj-breadcrumb-title tj-char-animation">Services</h2>
                        <p class="tj-breadcrumb-body"><span><a href="index.html">Home</a></span> <span class="spacing"><svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" clip-rule="evenodd" d="M16.1639 8.42265C16.4818 8.74057 16.4818 9.25948 16.1639 9.57739L9.93661 15.8045C9.6182 16.1229 9.10024 16.1229 8.78187 15.8045L8.43354 15.4562C8.11485 15.1375 8.11478 14.6198 8.4335 14.301L13.1574 9.57753C13.4762 9.25884 13.4762 8.74106 13.1574 8.42237L8.43354 3.69885C8.11478 3.38012 8.11481 2.86248 8.43357 2.54375L8.7819 2.19542C9.09982 1.87751 9.61872 1.87751 9.93664 2.19542L16.1639 8.42265ZM3.34094 2.19535C3.02271 1.87708 2.50426 1.87712 2.18602 2.19535L1.8377 2.54368C1.5196 2.86178 1.51957 3.38068 1.8377 3.69881L6.5614 8.42237C6.88012 8.7411 6.88012 9.25881 6.5614 9.57753L1.83766 14.3011C1.51943 14.6193 1.51946 15.138 1.83766 15.4562L2.18599 15.8045C2.50436 16.1229 3.02253 16.1229 3.34091 15.8045L9.01506 10.1302C10.6067 11.7203 10.2041 11.317 9.01622 10.129L9.56782 9.57739C9.88595 9.25926 9.88591 8.74074 9.56782 8.42262L3.34094 2.19535Z" fill="white" />
                          </svg></span> Services</p>
                    </div>
                </div>
            </div>
            <div class="tj-breadcrumb-bg-shape">
                <img src="{% static 'assets/images/breadcrumb/breadcrumb-bg-shape1.png' %}" alt="">
            </div>
        </section>
        <!-- Breadcrumb Area End-->

        <!-- Service Area Start-->
        <section class="tj-service-inner-page-area fix">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="tj-service-2-wrapper">
                        {% if services %}
                        {% for service in services %}
                        <div class="tj-service-2-item wow fadeInLeft" data-wow-delay=".5s">
                            <div class="tj-service-2-thumb">
                                {% if service.image %}
                                <img src="{{service.image.url}}" alt="">
                                {% endif %}
                            </div>
                            <div class="tj-service-2-box">
                                <div class="tj-service-2-wrap">
                                    <div class="tj-service-2-icon">
                                        <span><i class="flaticon-cleaning"></i></span>
                                    </div>
                                    <div class="tj-service-2-number">
                                        <span> {{ forloop.counter }}</span>
                                    </div>
                                </div>
                                <div class="tj-service-2-content">
                                    <h4 class="tj-service-2-title">
                                        <a href="{% url 'fresh:serviceDetails' service.slug %}"> {{service.name}}  </a></h4>
                                    <p class="tj-service-2-paragraph">{{service.description|truncatechars:145|safe}}</p>
                                    <div class="tj-service-2-button">
                                        <a class="tj-service-2-btn tj-arrow-btn" href="{% url 'fresh:serviceDetails' service.slug %}">Read More                                         
                                            <span class="icon_box">
                                                <i class="icon_first fa-regular fa-arrow-right"></i>
                                                <i class="icon_second fa-regular fa-arrow-right"></i>
                                            </span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        {% endif %}
                       
                    </div> 
                </div>
            </div>
            <div class="tj-service-2-bg-shape">
                <div class="tj-service-2-bg-shape-1">
                    <img src="{% static 'assets/images/service/service-2-bg-shape.png' %}" alt="Images">
                </div>
            </div>
        </section>
        <!-- Service Area End-->
        
    </main>

    <!-- Footer Area Start-->
    {% include 'partials/footer.html' %}
    <!-- Footer Area End-->

 
</body>

{% endblock content %}