Documents/freshfix/fresh/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import home,editabout,delete_abouts,listAbout,edit_about,add_about,editslide,edit_slide,delete_slide,add_slider,listSlider,addSlider,delete_logo, listLogos,getLogo,add_logo,update_service,edit_service,delete_service,listServices,about,service,blog,blogDetails,serviceDetails,contact,privacy,dashboard,addServices,add_service
from userauths.views import register,login_view,logout_view, check_mail,reset_password
from .views import addTeam,sendToMail,edit_team,add_team,delete_team,listTeam,update_team,addUs,add_us,listUs,delete_us,edit_us,update_us
from .views import addtestimonials,save_testimonials, listTestimonials,delete_testimonials,edit_testimonials,update_testimonial
from .views import  addBlog,add_Blog,listBlog,delete_Blog,edit_Blog,update_Blog,add_about2
from .views import  addContactAddress, add_ContactAddress, listContactAddress, delete_ContactAddress, edit_ContactAddress, update_ContactAddress
from .views import  blogByCategory,add_about3,addCategory,add_category,listCategory,delete_Category,edit_Category,update_Category,add_blog
from .views import getContactImage,listContactImage,add_ContactImage,delete_ContactImage, sendComment,listComments,delete_comment
from .views import  addPrivacy,add_PrivacyPolicy,listPrivacyPolicy,delete_PrivacyPolicy,edit_PrivacyPolicy,update_PrivacyPolicy
from .views import listUser,delete_User,listCode,delete_Code,edit_user,update_user

app_name = "fresh"

urlpatterns = [

    path("check-mail", check_mail, name="check_mail"),
    path("list-user", listUser, name="listUser"),
    path("delete-user/<int:id>/", delete_User, name="delete_User"),
    path("edit-user/<int:id>/", edit_user, name="edit_user"),
    path("update-user", update_user, name="update_user"),
    

    path("list-code", listCode, name="listCode"),
    path("delete-code/<int:id>/", delete_Code, name="delete_Code"),

    


    path("add-policy", addPrivacy, name="addPrivacy"),
    path("save-policy", add_PrivacyPolicy, name="add_PrivacyPolicy"),
    path("list-policy", listPrivacyPolicy, name="listPrivacyPolicy"),
    path("delete-policy/<int:id>/", delete_PrivacyPolicy, name="delete_PrivacyPolicy"),
    path("edit-policy/<int:id>/", edit_PrivacyPolicy, name="edit_PrivacyPolicy"),
    path("update-policy", update_PrivacyPolicy, name="update_PrivacyPolicy"),


    path("add-contact-image", getContactImage, name="getContactImage"),
    path("save-contact-image", listContactImage, name="listContactImage"),
    path("list-contact-image", add_ContactImage, name="add_ContactImage"),
    path("delete-contact-image/<int:id>/", delete_ContactImage, name="delete_ContactImage"),



    path("add-contact-address", addContactAddress, name="addContactAddress"),
    path("save-contact-address", add_ContactAddress, name="add_ContactAddress"),
    path("list-contact-address", listContactAddress, name="listContactAddress"),
    path("delete-contact-address/<int:id>/", delete_ContactAddress, name="delete_ContactAddress"),
    path("edit-contact-address/<int:id>/", edit_ContactAddress, name="edit_ContactAddress"),
    path("update-contact-address", update_ContactAddress, name="update_ContactAddress"), 
    
    
    


    path("add-Blog", addBlog, name="addBlog"),
    path("add-Blog", add_Blog, name="add_Blog"),
    path("list-Blog", listBlog, name="listBlog"),
    path("delete-Blog/<int:id>/", delete_Blog, name="delete_Blog"),
    path("edit-Blog/<int:id>/", edit_Blog, name="edit_Blog"),
    path("update-Blog", update_Blog, name="update_Blog"),
    path("submit-Blog", add_blog, name="add_blog"),
    


    path("add-Category", addCategory, name="addCategory"),
    path("add-Category", add_category, name="add_category"),
    path("list-Category", listCategory, name="listCategory"),
    path("delete-Category/<int:id>/", delete_Category, name="delete_Category"),
    path("edit-Category/<int:id>/", edit_Category, name="edit_Category"),
    path("update-Category", update_Category, name="update_Category"),










    path("add-testimonials", addtestimonials, name="addtestimonials"),
    path("save_testimonials", save_testimonials, name="save_testimonials"),
    path("list-testimonials", listTestimonials, name="listTestimonials"),
    path("delete_testimonials/<int:id>/", delete_testimonials, name="delete_testimonials"),
    path("edit_testimonials/<int:id>/", edit_testimonials, name="edit_testimonials"),
    path("update-testimonial", update_testimonial, name="update_testimonial"),
    path('', home, name='home'),
    path('about', about, name='about'),
    path('service', service, name='service'),
    path('blog', blog, name='blog'),
    path('blog-detail/<slug:slug>/', blogDetails, name='blogDetails'),
    path('blog-category/<slug:slug>/', blogByCategory, name='blogByCategory'),
    path('password-reset/<str:email>/', reset_password, name='reset_password'),
    
    
    path('service-detail/<slug:slug>', serviceDetails, name='serviceDetails'),
    path('contact', contact, name='contact'),
    path('addTeam', addTeam, name='addTeam'),
    path('add_team', add_team, name='add_team'),
    path('privacy', privacy, name='privacy'),
     path("register", register, name="register"),
     path("login", login_view, name="login_view"),
     path("logout", logout_view, name="logout_view"),
     path("dashboard", dashboard, name="dashboard"),
     path("add_logo", add_logo, name="add_logo"),
     path("add_about", add_about, name="add_about"),
     path("add_about", add_about2, name="add_about2"),
     path("add_about_", add_about3, name="add_about3"),
     path("list-about", listAbout, name="listAbout"),
     path("update-about", editabout, name="editabout"),     
     path("edit-about/<int:id>/", edit_about, name="edit_about"),
     path("delete-about/<int:id>/", delete_abouts, name="delete_abouts"),     
     path("getLogo", getLogo, name="getLogo"),
     path("update-service", update_service, name="update_service"),
     path("update-team", update_team, name="update_team"),
     path("add-services", addServices, name="addServices"),
     path('add-service/', add_service, name='add_service'),
     path('add-slider/', add_slider, name='add_slider'),
     path('add-slider/', addSlider, name='addSlider'),
     path('list-service/', listServices, name='listServices'),
     path('list-team/', listTeam, name='listTeam'),
     path('list-logos/', listLogos, name='listLogos'),
     path('list-slide/', listSlider, name='listSlider'),
     path('delete-service/<int:id>/', delete_service, name='delete_service'),
     path('delete-team/<int:id>/', delete_team, name='delete_team'),
     path('delete-logo/<int:id>/', delete_logo, name='delete_logo'),
     path('edit-service/<int:id>/', edit_service, name='edit_service'),
     path('edit-team/<int:id>/', edit_team, name='edit_team'),
     path('edit-slide/<int:id>/', edit_slide, name='edit_slide'),
     path('update-slide', editslide, name='editslide'),
     path('delete-slide/<int:id>/', delete_slide, name='delete_slide'),
    path("addus", addUs, name="addUs"),
    path("add-us", add_us, name="add_us"),
    path("list-us", listUs, name="listUs"),
    path("delete-us/<int:id>/", delete_us, name="delete_us"),
    path("edit-us/<int:id>/", edit_us, name="edit_us"),
    path("update-us", update_us, name="update_us"),
    path("send-mail", sendToMail, name="sendToMail"),     
    path("send-comment", sendComment, name="sendComment"),     
    path("list-comment", listComments, name="listComments"),     
    path("delete_comment/<int:id>/", delete_comment, name="delete_comment"),     
    
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Documents/freshfix/freshfix/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fresh.urls')),
]

Documents/freshfix/fresh/models.py
from django.db import models

from django.utils.text import slugify
from django.utils.timezone import now


class ContactAddress(models.Model):
    emailone = models.CharField(max_length=255)
    emailtwo = models.CharField(max_length=255)
    phoneone = models.CharField(max_length=255)
    phonetwo = models.CharField(max_length=255)
    addressone = models.CharField(max_length=255)
    addresstwo = models.CharField(max_length=255)
    workday = models.CharField(max_length=255)
    worktime = models.CharField(max_length=255)
    socialtext = models.TextField(null=True, blank=True, default="socialtext")
    facebook = models.CharField(max_length=255)
    twitter = models.CharField(max_length=255)
    whatsapp = models.CharField(max_length=255)
    instagram = models.CharField(max_length=255)
    linkedin = models.CharField(max_length=255)
    footertext = models.CharField(max_length=255)
    created_at = models.DateTimeField(default=now, editable=False)  # Automatically sets to the current date and time

    def __str__(self):
        return self.emailone
    

class Team(models.Model):
    name = models.CharField(max_length=255)
    job = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    link1 = models.CharField(max_length=255)
    link2 = models.CharField(max_length=255)
    link3 = models.CharField(max_length=255)
    link4 = models.CharField(max_length=255)
    slug = models.CharField(max_length=255)
    image = models.ImageField(upload_to='service/', null=True)
    created_at = models.DateTimeField(default=now, editable=False)  # Automatically sets to the current date and time

    def __str__(self):
        return self.name
    
class BeforeAfter(models.Model):
    before = models.ImageField(upload_to='service/', null=True)
    after = models.ImageField(upload_to='service/', null=True)
    created_at = models.DateTimeField(default=now, editable=False)  # Automatically sets to the current date and time

    def __str__(self):
        return self.created_at
    
class WhyChoose(models.Model):
    header = models.CharField(max_length=255, null=True)
    paragraph = models.CharField(max_length=255, null=True)
    headerone = models.CharField(max_length=255)
    headertwo = models.CharField(max_length=255)
    headerthree = models.CharField(max_length=255)
    paragraphone = models.CharField(max_length=255)
    paragraphtwo = models.CharField(max_length=255)
    paragraphthree = models.CharField(max_length=255)
    imageone = models.ImageField(upload_to='service/', null=True)
    imagetwo = models.ImageField(upload_to='service/', null=True)
    created_at = models.DateTimeField(default=now, editable=False)  # Automatically sets to the current date and time

    def __str__(self):
        return self.name
    
class Book(models.Model):
    name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    subject = models.CharField(max_length=255)
    service = models.CharField(max_length=255)
    message = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    created_at = models.DateTimeField(default=now, editable=False)  # Automatically sets to the current date and time

    def __str__(self):
        return self.name

class Testimonial(models.Model):
    name = models.CharField(max_length=255)
    title = models.CharField(max_length=255)
    paragraph = models.CharField(max_length=255)
    image = models.ImageField(upload_to='service/', null=True)
    created_at = models.DateTimeField(default=now, editable=False)  # Automatically sets to the current date and time

    def __str__(self):
        return self.name
    

class Message(models.Model):
    name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    phone = models.CharField(max_length=255, null=True)
    subject = models.CharField(max_length=255) 
    service = models.CharField(max_length=255) 
    message = models.CharField(max_length=255) 
    created_at = models.DateTimeField(default=now, editable=False)  # Automatically sets to the current date and time

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.CharField(max_length=255, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name
    

class Service(models.Model):
    name = models.CharField(max_length=255)
    slug = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='services', null=True)
    image = models.ImageField(upload_to='service/', null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    compare_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    description = models.TextField()
    created_at = models.DateTimeField(default=now, editable=False)  # Automatically sets to the current date and time

    def __str__(self):
        return self.name

class Image(models.Model):
    service = models.ForeignKey(Service, related_name='images', on_delete=models.CASCADE)
    file = models.ImageField(upload_to='services/')
    created_at = models.DateTimeField(default=now, editable=False)  # Automatically sets to the current date and time



class PrivacyPolicy(models.Model):
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.created_at



class Blog(models.Model):
    name = models.CharField(max_length=255)
    slug = models.CharField(max_length=255, unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='blogs')
    image = models.ImageField(upload_to='blogs/featured/', null=True, blank=True)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class BlogImage(models.Model):
    blog = models.ForeignKey(Blog, related_name='images', on_delete=models.CASCADE)
    file = models.ImageField(upload_to='blogs/gallery/')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.blog.name} - Image {self.id}"
    
class Comments(models.Model):
    fname = models.CharField(max_length=255)
    lname = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    website = models.CharField(max_length=255)
    comment = models.CharField(max_length=255)
    post = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='blogs', null=True)
    created_at = models.DateTimeField(default=now, editable=False)  # Automatically sets to the current date and time

    def __str__(self):
        return self.fname

class Logo(models.Model):
    logo = models.ImageField(upload_to='logo/')
    created_at = models.DateTimeField(default=now, editable=False)  # Automatically sets to the current date and time



class ContactImage(models.Model):
    image = models.ImageField(upload_to='image/')
    created_at = models.DateTimeField(default=now, editable=False)  # Automatically sets to the current date and time



class SliderSection(models.Model):
    sub_title = models.CharField(max_length=255, help_text="Short subtitle for the slider")
    title = models.CharField(max_length=255, help_text="Main title for the slider")
    paragraph = models.TextField(help_text="Description paragraph for the slider")
    btntext = models.TextField(help_text="Button text for the slider")
    contact_number = models.CharField(max_length=20, help_text="Contact number to display")
    contact_link = models.URLField(help_text="Link for the 'Describe More' button")
    background_image = models.ImageField(upload_to='slider/backgrounds/', help_text="Background image")
    slider_image = models.ImageField(upload_to='slider/images/', help_text="Main image for the slider")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    


class AboutSection(models.Model):
    sub_title = models.CharField(max_length=255, help_text="Short subtitle for the slider")
    title = models.CharField(max_length=255, help_text="Main title for the slider")
    paragraph = models.TextField(help_text="Description paragraph for the slider")
    btntext = models.TextField(help_text="Button text for the slider")
    list_one = models.CharField(max_length=20, help_text="Contact number to display")
    list_two = models.CharField(max_length=20, help_text="Contact number to display")
    list_three = models.CharField(max_length=20, help_text="Contact number to display")
    name = models.CharField(max_length=20, help_text="Contact number to display", null=True)
    job = models.CharField(max_length=20, help_text="Contact number to display", null=True)
    background_image = models.ImageField(upload_to='slider/backgrounds/', help_text="Background image")
    slider_image = models.ImageField(upload_to='slider/images/', help_text="Main image for the slider")
    profile = models.ImageField(upload_to='slider/images/', help_text="Main image for the slider")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

Documents/freshfix/templates/partials/b.html
{%  load static %}
 

 


    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        
        {% block content %}

        {% endblock content %}



    </body>
    </html>

Documents/freshfix/templates/partials/backtotop.html
{% load static %}

<div class="back-to-top-wrapper">
    <button id="back_to_top" type="button" class="back-to-top-btn">
        <svg width="12" height="7" viewBox="0 0 12 7" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M11 6L6 1L1 6" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
        </svg>
    </button>
</div>

Documents/freshfix/templates/partials/categories.html
<ul>
    {% if categories %}
    {% for category in categories %}
        <li class="cat-item">
            <a href="{% url 'fresh:blogByCategory' category.slug %}">
                {{ category.name }}
                <!-- Correctly showing the count of blogs related to this category -->
                <span>({{ category.blog_set.count }})</span>  <!-- Assuming Blog has a ForeignKey to Category -->
            </a>
        </li> 
    {% endfor %}
{% endif %}

</ul>

Documents/freshfix/templates/partials/fixedheadertop.html
{% load static %}

<header class="tj-header-sticky header-sticky d-none">
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <div class="tj-header-bottom-wrapper">
                    <div class="tj-header-sticky-mobile-logo">
                        <a href="/">
                            <img src="{% static 'assets/images/logo/freshfix05.png' %}" alt="Logos">
                        </a>
                    </div>
                    <div class="tj-header-bottom-left d-none d-xl-block">
                        <div class="mainmenu-wrapper">
                            <div class="mainmenu-box">
                                {% include 'partials/mainmenu.html' %}
                            </div>
                        </div>
                    </div>
                    <div class="tj-header-bottom-right">
                        <div class="tj-header-bottom-search d-none d-xl-block">
                            <button class="tj-header-search tj-search-popup"><i class="fa-regular fa-magnifying-glass"></i></button>
                        </div>

                        <div class="tj-header-bottom-cart d-none d-sm-block">
                            {% if user.is_authenticated %}
                            <!-- Show Logout Link if the user is logged in -->
                            <a href="{% url 'fresh:dashboard' %}" class=""><i class="flaticon-user"></i></a> <!-- Replace with appropriate logout icon -->
                        {% else %}
                            <!-- Show Register Link if the user is not logged in -->
                            <a href="{% url 'fresh:register' %}" class=""><i class="flaticon-user"></i></a>
                        {% endif %}
                        </div>
                        <div class="tj-header-bottom-mobile-button d-block d-xl-none">
                            {% if user.is_authenticated %}
                            <!-- Show Logout Link if the user is logged in -->
                            <a href="{% url 'fresh:dashboard' %}" class=""><i class="flaticon-user"></i></a> <!-- Replace with appropriate logout icon -->
                        {% else %}
                            <!-- Show Register Link if the user is not logged in -->
                            <a href="{% url 'fresh:register' %}" class=""><i class="flaticon-user"></i></a>
                        {% endif %}
                        </div>


                        <div class="tj-header-bottom-mobile-button d-block d-xl-none">
                            <button class="tj-header-bottom-mobile-btn menu-bar">
                                <span></span>
                                <span></span>
                                <span></span>
                                <span></span>
                            </button>
                        </div>

                        <div class="tj-header-sticky-button d-none d-md-block">
                            <a class="tj-primary-btn tj-hover-btn" href="{% url  'fresh:contact' %}"><span>Get a quote <i class="flaticon-start"></i></span>
                                <div class="tj-hover-btn-circle-dot"></div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

Documents/freshfix/templates/partials/footer.html
{% load static %}


<footer class="tj-footer-area">
    <div class="tj-footer-bg-shape">
        <img src="{% static 'assets/images/footer/footer-bg-shape.png' %}" alt="">
    </div>
    <div class="tj-footer-top">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="tj-footer-top-wrapper">
                        <div class="tj-footer-top-wrap">
                            <div class="tj-footer-top-wrap-icon">
                                <span><i class="flaticon-email-2"></i></span>
                            </div>
                            <div class="tj-footer-top-wrap-content">
                                <span class="sub-title">Send Email</span>
                                <span><a href="mailto:helpcleaning@gmail.com">{{contactaddress.emailone}}</a></span>
                            </div>
                        </div>
                        <div class="tj-footer-top-wrap">
                            <div class="tj-footer-top-wrap-icon">
                                <span><i class="flaticon-call"></i></span>
                            </div>
                            <div class="tj-footer-top-wrap-content">
                                <span class="sub-title">Need Any Cleaning Help</span>
                                <span><a href="tel:+208555-0112">{{contactaddress.phoneone}}</a></span>
                            </div>
                        </div>
                        <div class="tj-footer-top-wrap">
                            <div class="tj-footer-top-wrap-icon">
                                <span><i class="flaticon-location"></i></span>
                            </div>
                            <div class="tj-footer-top-wrap-content">
                                <span class="sub-title">Our Address</span>
                                <span class="location">{{contactaddress.addresstwo}}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="tj-footer-bottom">
        <div class="container">
            <div class="row tj-footer-bottom-row">
                <div class="col-xl-4 col-lg-3 col-md-6 col-sm-6">
                    <div class="tj-footer-widget tj-footer-col-1">
                        <div class="tj-footer-widget-logo">
                            {% if logo %}
                        
                            <a href="/"><img src="{{ logo.logo.url }}" alt="FreshFix" ></a>
                        
                            {% else %}
                
                            {% endif %}
                        </div>
                        <div class="tj-footer-widget-paragraph">
                            <p class="tj-footer-widget-paragraph">{{contactaddress.footertext}}</p>
                        </div>
                        <div class="tj-footer-widget-socail">
                            <ul>
                                <li><a href="{{contactaddress.facebook}}"><i class="fa-brands fa-facebook-f fa-fw"></i></a></li>
                                <li><a href="{{contactaddress.twitter}}"><i class="fa-brands fa-twitter"></i></a></li>
                                <li><a href="{{contactaddress.linkedin}}"><i class="fa-brands fa-linkedin-in"></i></a></li>
                                <li><a href="{{contactaddress.instagram}}"><i class="fa-brands fa-instagram"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-3 col-md-6 col-sm-6">
                    <div class="tj-footer-widget widget_nav_menu tj-footer-col-2">
                        <h4 class="tj-footer-widget-title">Services</h4>
                        <div class="tj-footer-widget-menu">
                            <ul>
                                      {% if services %}
                                    {% for service in services %}
                                <li><a href="#">
                                    <span><i class="flaticon-start"></i></span>  {{service.name}}  </a>
                                </li> 
                                {% endfor %}
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-xl-2 col-lg-2 col-md-6 col-sm-6">
                    <div class="tj-footer-widget widget_nav_menu tj-footer-col-3">
                        <h4 class="tj-footer-widget-title">Quick Link</h4>
                        <div class="tj-footer-widget-menu">
                            <ul>
                                <li><a href="/"><span><i class="flaticon-start"></i></span> Home</a></li>
                                <li><a href="{% url 'fresh:about' %}"><span><i class="flaticon-start"></i></span> About</a></li>
                                <li><a href="{% url 'fresh:service' %}"><span><i class="flaticon-start"></i></span> Services</a></li>
                                <li><a href="{% url 'fresh:blog' %}"><span><i class="flaticon-start"></i></span> News</a></li>
                                <li><a href="{% url 'fresh:privacy' %}"><span><i class="flaticon-start"></i></span> Privacy</a></li>
                                <li><a href="{% url 'fresh:contact' %}"><span><i class="flaticon-start"></i></span> Contact </a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6">
                    <div class="tj-footer-widget tj-footer-col-4">
                        <h4 class="tj-footer-widget-title">Resent Post</h4> 
                        
                        {% if recntPost %}
                        {% for post in recntPost %}
                        <div class="tj-footer-widget-post">
                            <div class="tj-footer-widget-post-thumb">
                                <a href="{% url 'fresh:blogDetails' post.slug %}">
                                    {% if post.image %}
                                    <img class="attachment-thumbnail size-thumbnail wp-post-image" src="{{ post.image.url }}" alt="{{ post.name }}">
                                        {% endif %}
                                </a>
                            </div>
                            <div class="tj-footer-widget-post-content">
                                <div class="tj-footer-widget-post-date">
                                    <span><i class="flaticon-calendar"></i>  {{ post.created_at|date:"b d Y" }}</span>
                                </div>
                                <h4 class="tj-footer-widget-post-title">
                                    <a href="{% url 'fresh:blogDetails' post.slug %}">{{ post.name|truncatechars:10 }}</a>
                                </h4>
                            </div>
                        </div>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="tj-footer-copyright">
        <div class="container">
            <div class="row align-items-center">
                <div class="tj-footer-copyright-wrapper">
                    <div class="tj-footer-copyright-content">
                        <p class="tj-footer-copyright-paragraph">Copyright@ 2024 <a href="https://themeforest.net/user/theme-junction">
                            FreshFiz.</a> All Rights Reserved.</p>
                    </div>
                    <div class="tj-footer-copyright-menu">
                        <ul>
                            <li><a href="{% url 'fresh:privacy' %}">Setting & Privacy</a></li>
                            <!-- <li><a href="#">FAQ</a></li>
                            <li><a href="#">Support </a></li> -->
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

Documents/freshfix/templates/partials/mainmenu.html
{% load static %}


<div class="mainmenu main-mobile-menu d-none d-lg-inline-block">
    <ul>
        <li><a href="/">Home</a></li>
        <li><a href="{% url 'fresh:about' %}">About</a></li>
        <!-- <li class="has-dropdown">
            <a href="{% url 'fresh:about' %}">About</a>
            <ul class="sub-menu">
                <li><a href="team.html">Team</a></li>
                <li><a href="team-details.html">Team Details</a></li>
            </ul>
        </li> -->
        <li><a href="{% url 'fresh:service' %}">Services</a></li>
    
        </li>
        <li> <a href="{% url 'fresh:blog' %}">News</a></li>
        <li><a href="{% url 'fresh:privacy' %}">Privacy</a></li>
        <li><a href="{% url 'fresh:contact' %}">Contact</a></li>
    </ul>
</div>

Documents/freshfix/templates/partials/populartags.html
{% load static %}


{% if tags %}
{% for  tag  in tags %}

<a href="{% url 'fresh:blogByCategory' tag.slug %}"> {{tag.name}} </a>  
{% endfor %}
{% endif %}